/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PostMsgRouteImport } from './routes/postMsg'
import { Route as MsgBoxRouteImport } from './routes/msgBox'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FindUserRouteImport } from './routes/findUser'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const PostMsgRoute = PostMsgRouteImport.update({
  id: '/postMsg',
  path: '/postMsg',
  getParentRoute: () => rootRouteImport,
} as any)
const MsgBoxRoute = MsgBoxRouteImport.update({
  id: '/msgBox',
  path: '/msgBox',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FindUserRoute = FindUserRouteImport.update({
  id: '/findUser',
  path: '/findUser',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/findUser': typeof FindUserRoute
  '/login': typeof LoginRoute
  '/msgBox': typeof MsgBoxRoute
  '/postMsg': typeof PostMsgRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/findUser': typeof FindUserRoute
  '/login': typeof LoginRoute
  '/msgBox': typeof MsgBoxRoute
  '/postMsg': typeof PostMsgRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/findUser': typeof FindUserRoute
  '/login': typeof LoginRoute
  '/msgBox': typeof MsgBoxRoute
  '/postMsg': typeof PostMsgRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/findUser' | '/login' | '/msgBox' | '/postMsg'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/findUser' | '/login' | '/msgBox' | '/postMsg'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/findUser'
    | '/login'
    | '/msgBox'
    | '/postMsg'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FindUserRoute: typeof FindUserRoute
  LoginRoute: typeof LoginRoute
  MsgBoxRoute: typeof MsgBoxRoute
  PostMsgRoute: typeof PostMsgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/postMsg': {
      id: '/postMsg'
      path: '/postMsg'
      fullPath: '/postMsg'
      preLoaderRoute: typeof PostMsgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/msgBox': {
      id: '/msgBox'
      path: '/msgBox'
      fullPath: '/msgBox'
      preLoaderRoute: typeof MsgBoxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findUser': {
      id: '/findUser'
      path: '/findUser'
      fullPath: '/findUser'
      preLoaderRoute: typeof FindUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FindUserRoute: FindUserRoute,
  LoginRoute: LoginRoute,
  MsgBoxRoute: MsgBoxRoute,
  PostMsgRoute: PostMsgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
